# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi.yaml:
  operation-2xx-response:
    - '#/paths/~1v3~1droplets~1{droplet_guid}~1download/get/responses'
    - '#/paths/~1v3~1packages~1{guid}~1download/get/responses'
  security-defined:
    - '#/paths/~1v3~1buildpacks/get'
    - '#/paths/~1v3~1users/get'
    - '#/paths/~1v3~1users/post'
    - '#/paths/~1v3~1droplets/get'
    - '#/paths/~1v3~1domains/get'
    - '#/paths/~1v3~1deployments/get'
    - '#/paths/~1v3~1feature_flags/get'
    - '#/paths/~1v3~1builds/get'
    - '#/paths/~1v3~1audit_events/get'
    - '#/paths/~1v3~1apps/get'
