# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
apis/cf/latest/paths/Packages.yaml:
  operation-2xx-response:
    - '#/~1v3~1packages~1{guid}~1download/get/responses'
