/v3/deployments:
  get:
    summary: List deployments
    description: Retrieve all deployments.
    operationId: listDeployments
    tags:
    - Deployments
    parameters:
    - $ref: '../components/parameters/Page.yaml'
    - $ref: '../components/parameters/PerPage.yaml'
    - $ref: '../components/parameters/OrderBy.yaml'
    - $ref: '../components/parameters/CreatedAts.yaml'
    - $ref: '../components/parameters/UpdatedAts.yaml'
    - $ref: '../components/parameters/LabelSelector.yaml'
    - name: app_guids
      in: query
      schema:
        type: array
        items:
          type: string
      description: Comma-delimited list of app GUIDs to filter by
    - name: states
      in: query
      schema:
        type: array
        items:
          type: string
      description: Comma-delimited list of states to filter by
    - name: status_reasons
      in: query
      schema:
        type: array
        items:
          type: string
          enum:
          - DEPLOYING
          - PAUSED
          - CANCELING
          - DEPLOYED
          - CANCELED
          - SUPERSEDED
      description: Comma-delimited list of status reasons to filter by
    - name: status_values
      in: query
      schema:
        type: array
        items:
          type: string
          enum:
          - ACTIVE
          - FINALIZED
      description: Comma-delimited list of status values to filter by
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '../components/schemas/DeploymentList.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '400':
        $ref: '../components/responses/BadRequest.yaml'
      '500':
        $ref: '../components/responses/500.yaml'
      '502':
        $ref: '../components/responses/BadGateway.yaml'
      '503':
        $ref: '../components/responses/ServiceUnavailable.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
      '409':
        $ref: '../components/responses/Conflict.yaml'
  post:
    summary: Create a deployment
    description: When you create a new deployment you can either provide a specific
      droplet or revision to deploy. If no revision or droplet is provided, the droplet
      associated with the app is deployed.
    operationId: createDeployment
    tags:
    - Deployments
    requestBody:
      description: Deployment object that needs to be created
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              relationships:
                $ref: '../components/schemas/Relationships.yaml'
              strategy:
                type: string
                enum:
                - rolling
                - canary
              droplet:
                $ref: '../components/schemas/Relationship.yaml'
              revision:
                $ref: '../components/schemas/Relationship.yaml'
              metadata:
                $ref: '../components/schemas/Metadata.yaml'
    responses:
      '201':
        description: Successfully created deployment
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Deployment.yaml'
        links:
          app:
            operationId: getApp
            parameters:
              guid: $response.body#/relationships/app/data/guid
            description: Retrieve the app for this deployment
          droplet:
            operationId: getDroplet
            parameters:
              guid: $response.body#/droplet/data/guid
            description: Retrieve the droplet for this deployment
          previous_droplet:
            operationId: getDroplet
            parameters:
              guid: $response.body#/previous_droplet/data/guid
            description: Retrieve the previous droplet for this deployment
      '400':
        $ref: '../components/responses/BadRequest.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
      '500':
        $ref: '../components/responses/500.yaml'
      '503':
        $ref: '../components/responses/ServiceUnavailable.yaml'
      '409':
        $ref: '../components/responses/Conflict.yaml'
/v3/deployments/{guid}:
  get:
    summary: Get a deployment
    description: Retrieve a deployment.
    operationId: getDeployment
    tags:
    - Deployments
    parameters:
    - $ref: '../components/parameters/Guid.yaml'
    responses:
      '200':
        description: Successfully retrieved deployment
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Deployment.yaml'
        links:
          app:
            operationId: getApp
            parameters:
              guid: $response.body#/relationships/app/data/guid
            description: Retrieve the app for this deployment
          droplet:
            operationId: getDroplet
            parameters:
              guid: $response.body#/droplet/data/guid
            description: Retrieve the droplet for this deployment
          previous_droplet:
            operationId: getDroplet
            parameters:
              guid: $response.body#/previous_droplet/data/guid
            description: Retrieve the previous droplet for this deployment
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
  patch:
    summary: Update a deployment
    description: Update a deployment.
    operationId: updateDeployment
    tags:
    - Deployments
    parameters:
    - $ref: '../components/parameters/Guid.yaml'
    requestBody:
      description: Deployment object that needs to be updated
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                $ref: '../components/schemas/Metadata.yaml'
            description: Request schema for updating a deployment
    responses:
      '200':
        description: Successfully updated deployment
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Deployment.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
      '400':
        $ref: '../components/responses/BadRequest.yaml'
      '500':
        $ref: '../components/responses/500.yaml'
      '503':
        $ref: '../components/responses/ServiceUnavailable.yaml'
      '409':
        $ref: '../components/responses/Conflict.yaml'
/v3/deployments/{guid}/actions/cancel:
  post:
    summary: Cancel a deployment
    description: Cancel a deployment.
    operationId: cancelDeployment
    tags:
    - Deployments
    parameters:
    - $ref: '../components/parameters/Guid.yaml'
    responses:
      '200':
        description: Successfully canceled deployment
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Deployment.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
/v3/deployments/{guid}/actions/continue:
  post:
    summary: Continue a deployment
    description: Continue a deployment.
    operationId: continueDeployment
    tags:
    - Deployments
    parameters:
    - $ref: '../components/parameters/Guid.yaml'
    responses:
      '200':
        description: Successfully continued deployment
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Deployment.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
