/v3/environment_variable_groups/{name}:
  get:
    summary: Get an environment variable group
    description: Retrieve an environment variable group.
    operationId: getEnvironmentVariableGroup
    tags:
    - Environment Variable Groups
    parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
        enum:
        - running
        - staging
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '../components/schemas/EnvironmentVariableGroup.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '500':
        $ref: '../components/responses/500.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '400':
        $ref: '../components/responses/BadRequest.yaml'
      '502':
        $ref: '../components/responses/BadGateway.yaml'
      '503':
        $ref: '../components/responses/ServiceUnavailable.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
      '409':
        $ref: '../components/responses/Conflict.yaml'
  patch:
    summary: Update environment variable group
    description: 'Update the environment variable group. The variables given in the
      request will be merged with the existing environment variable group. Any requested
      variables with a value of `null` will be removed from the group. Environment
      variable names may not start with VCAP_. PORT is not a valid environment variable.


      Variables updated in the **running** environment variable group will not take
      effect until apps are restarted.'
    operationId: updateEnvironmentVariableGroup
    tags:
    - Environment Variable Groups
    parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
        enum:
        - running
        - staging
    requestBody:
      description: The environment variables to update
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              var:
                type: object
                additionalProperties:
                  type: string
                description: Environment variables to inject; keys and values must
                  be strings
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '../components/schemas/EnvironmentVariableGroup.yaml'
      '400':
        $ref: '../components/responses/BadRequest.yaml'
      '401':
        $ref: '../components/responses/Unauthorized.yaml'
      '403':
        $ref: '../components/responses/Forbidden.yaml'
      '500':
        $ref: '../components/responses/500.yaml'
      '404':
        $ref: '../components/responses/NotFound.yaml'
      '422':
        $ref: '../components/responses/UnprocessableEntity.yaml'
      '503':
        $ref: '../components/responses/ServiceUnavailable.yaml'
      '409':
        $ref: '../components/responses/Conflict.yaml'
