name: Test CF API V3 Documentation
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: yarn install
      - name: Stats
        run: yarn run redocly stats --format markdown >> $GITHUB_STEP_SUMMARY
      - name: Lint
        run: |
          yarn run redocly lint --format markdown >> $GITHUB_STEP_SUMMARY || true
          yarn run redocly lint --format github-actions
      - name: Build
        run: yarn build