name: Test CF API V3 Documentation
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: yarn global add @redocly/cli
      - name: Stats
        run: redocly stats openapi.yaml --format markdown >> $GITHUB_STEP_SUMMARY
      - name: Lint
        run: |
          redocly lint openapi.yaml --format markdown >> $GITHUB_STEP_SUMMARY || true
          redocly lint openapi.yaml --format github-actions
      - name: Build
        run: redocly build-docs openapi.yaml -o index.html